### ISSUE TITLE
Prometheus Telemetry watcher consuming all memory in ETS table

### ISSUE THREAD

**Issue by drewble** [theblitzapp/prometheus_telemetry_elixir#22]
Our memory usage graph exhibits a pattern of filling to the max and flushing
![Screen Shot 2022-12-20 at 11 51 09 AM](https://user-images.githubusercontent.com/2472733/208748174-df140b61-f3e3-4db8-82f2-ac6b831c315f.png)

Looking at the Phoenix LiveDashboard, it appears that ETS is driving the memory usage, and the ETS tab implicates the `:prometheus_telemetry_<Integer>_metrics_watcher_dist` as the memory hog. I haven't been able to figure out if we have a misconfiguration, or where the `:prometheus_telemetry` package is filling an ETS table to backtrace how it is getting so full. It might be our fault, but it might be a bug.
![Screen Shot 2022-12-20 at 11 50 57 AM](https://user-images.githubusercontent.com/2472733/208748610-69cb25f2-8b2c-49c1-96ce-dc7375c42e94.png)

Not sure if it matters, but we did diverge from the setup instructions in the documentation so we could serve the `/metrics` endpoint on port 4000. We simply set up a route/controller and configured `PrometheusTelementry` in the `start/2` function of our `application.ex` module.

```elixir
defmodule MyAppWeb.MetricsController do
  use MyAppWeb, :controller

  action_fallback MyAppWeb.FallbackController

  def index(conn, _params) do
    metrics = PrometheusTelemetry.get_metrics_string()

    conn
    |> put_resp_content_type("text/plain")
    |> send_resp(200, metrics)
  end
end
```

```elixir
# application.ex

def start (_type, _args) do
  children = [
    ...,
    # Start Prometheus Endpoint
      {PrometheusTelemetry,
       metrics: [
         PrometheusTelemetry.Metrics.Ecto.metrics(:consumer_api),
         PrometheusTelemetry.Metrics.Cowboy.metrics(),
         PrometheusTelemetry.Metrics.Phoenix.metrics(),
         PrometheusTelemetry.Metrics.GraphQL.metrics(),
         PrometheusTelemetry.Metrics.VM.metrics()
       ]}
  ]

  ...
end
```

**Comment by MikaAK** [comment]
We've also seen this behaviour! This is actually an underlying ets table from https://github.com/beam-telemetry/telemetry_metrics_prometheus_core

Some ideas I've thought of are misconfiguration, or potentially metric duplication. I will investigate this week

**Comment by MikaAK** [comment]
https://github.com/beam-telemetry/telemetry_metrics_prometheus_core/issues/52

**Comment by MikaAK** [comment]
@drewble I just want to confirm a couple things, after doing some testing, we mostly seem to be fine on memory as long as `PrometheusTelemetry.get_supervisors_metrics_string(supervisors)` is getting called (the function that gets called when calling the exporter when `exporter_enabled?: true`)

**Comment by MikaAK** [comment]
Gonna close this, @drewble  if it's still happening for you lemme know
